Feature/gpx 567
gepaplexx/ansible-role-terraform pull request #8
Opened 2023-01-10 13:27 UTC by sgartner03

GPX-567: Actions starten jeden Montag um 07:00

2023-01-10 14:15 UTC, Lucostus approved these changes
LGTM

2023-01-12 08:41 UTC, gattma requested changes

2023-01-12 08:41 UTC, gattma commented on .github/workflows/3-main.yml
> +    - cron: "0 7 * * 1"
Bitte Ausführungszeit anpassen (0 0 * * 1).

2023-01-12 08:41 UTC, gattma commented on .github/workflows/2-pull-request.yml
> +    - cron: "0 7 * * 1"
Hier wieder entfernen.

2023-01-12 08:41 UTC, gattma commented on .github/workflows/1-develop.yml
> +    - cron: "0 7 * * 1"
Hier wieder entfernen.

2023-01-19 06:40 UTC, gattma approved these changes

2023-01-19 08:27 UTC, merged